language: elm
elm:
- latest-0.19.1
elm-test: 0.19.1
elm-format: 0.8.2
before_install: npm install parcel-bundler
script:
- npm test
- parcel build src/index.html --public-url ./
deploy:
  github_token: "$GITHUB_TOKEN"
  keep_history: true
  local_dir: dist
  provider: pages
  skip_cleanup: true
  on:
    branch: release
env:
  global:
    secure: ihN2kriDsE0ReU/QaV53IP07khdOeY4w2/n9abXZL42Oqcv+66H8IvzRkDaYrO/aqTrGh4DC7xEy33QalyOvmaKPDspQj0C++MZmHlOHPaEsaZUOvO3HSOz8LsIoWtktKVPB3VqBlKx/ehAgWVr8a+V/uV7kVQwnbBW3l2o6rAMHh7MStaKLF7QAlX9R61s7WyhXG2dQ/AzohxO2PPX/3wA8ghNBL6XJyVPbLDMwcDQBYGbSgViiSFAa3x5SmJ9sd+fL+P/+EJuimTwhPAPwrk9CiMAVWAHBZcg8f6eeXd0qHqkQ13l5eKtgNxxZHmE8k7xhRe5j4VMdDgPhcs33WjVy74mc8HWvp+xjg2vEUBjHmdXFPjao8Yrj1ChuNRmVOgJQ67iQCgpxCqx+ymmtS5UVbihQf6uXJ1EO27/xbaANjse8yWsddct4X7FfPaqOn5IAtV6Klo451N+Ps8HtrAAMR+mcEnYCtJ+KosrJrxC2YEUlCl+UahddtcQeyzJcdDgqcjC6YOJvEMtI/aS2GvBAb9g30mGImB6RjMjJU0V5tTOjbrstsa5ZhP2I7pHyShHhbfqSCqqOWR9nTd1tqoT9aa4w8eNm6KaTLjwmn/HMfsagwNZ0N8ZSU+8/SbHsb7FJkuRr7ciMhwGvBYEmLSGdBvJWYBgy/+tM2o+zG+Y=
